modelname   : LightSourceAndShadow
modelcomment: >
    Template for model pages. 
baseurl     : /LightSourceAndShadow
devname     : VicCastillo 
accountname : STEM-Dev
preurl      : https://github.com/STEM-Dev
#
gems:
  - jekyll-sitemap
markdown: redcarpet
exclude:  ['NIL']
encoding: UTF-8

