modelname   : LightSourceAndShadow
modelcomment: >
    NetLogo Model of Light source(s), a movable screen, and a light-sensitive film used for an introductory course on modeling. 
baseurl     : /LightSourceAndShadow
preurl      : https://github.com/VicCastillo
#
markdown : redcarpet
exclude  : ['NIL']
encoding : UTF-8
