modelname   : LightSourceAndShadow
modelcomment: >
    NetLogo Model of Light source(s), a movable screen, and a light-sensitive film used for an introductory course on modeling. 
baseurl     : /LightSourceAndShadow
devname     : VicCastillo 
accountname : STEM-Dev
preurl      : https://github.com/STEM-Dev
#
gems:
  - jekyll-sitemap
markdown: redcarpet
exclude:  ['NIL']
encoding: UTF-8

